{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/roshancharlie/College-Chatbot-Using-ML-and-NLP/blob/main/Chatbot.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Importing The Neccesary Libraries"
      ],
      "metadata": {
        "id": "etmFQ8Um9nik"
      }
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "sJj-U60xSq2C"
      },
      "outputs": [],
      "source": [
        "import nltk\n",
        "import json\n",
        "from nltk.corpus import wordnet\n",
        "from nltk.stem import WordNetLemmatizer\n",
        "import numpy as np\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.optim as optim\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "import random\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Creating Query-Based Intents for the Dataset"
      ],
      "metadata": {
        "id": "k-9rfsFB9xZV"
      }
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "id": "xaHOpKhSSsRR"
      },
      "outputs": [],
      "source": [
        "intents = {\n",
        "  \"intents\": [\n",
        "    {\n",
        "      \"tag\": \"greeting\",\n",
        "      \"patterns\": [\"Hi\", \"Hello\", \"Hey\", \"Good day\", \"How are you?\"],\n",
        "      \"responses\": [\"Hello!\", \"Good to see you!\", \"Hi there, how can I help?\"],\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"farewell\",\n",
        "      \"patterns\": [\"Goodbye\", \"Bye\", \"See you later\", \"Talk to you later\"],\n",
        "      \"responses\": [\"Sad to see you go :(\", \"Goodbye!\", \"Come back soon!\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"creator\",\n",
        "      \"patterns\": [\"Who created you?\", \"Who is your developer?\", \"Who made you?\"],\n",
        "      \"responses\": [\"I was created by Roshan Sinha.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"identity\",\n",
        "      \"patterns\": [\"What is your name?\", \"What should I call you?\", \"Who are you?\",\"What are you\",\"Introduce Yourself\"],\n",
        "      \"responses\": [\"You can call me Mind Reader. I'm a Chatbot.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"communication\",\n",
        "      \"patterns\": [\"How can I communicate with the university or contact my ward?\", \"What are the communication channels for students and parents?\"],\n",
        "      \"responses\": [\"You can communicate with the university through our official email, helpline number, or by visiting the respective department. For parents, we provide regular updates through email and dedicated portals.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"casual_greeting\",\n",
        "      \"patterns\": [\"What's up?\", \"How are you?\", \"How you doing?\"],\n",
        "       \"responses\": [\"I'm here to assist you with any questions or information you need. How can I assist you today?\"]\n",
        "\n",
        "     },\n",
        "    {\n",
        "      \"tag\": \"good_morning\",\n",
        "      \"patterns\": [\"Good morning\", \"Morning\"],\n",
        "      \"responses\": [\"Good morning! How can I assist you today?\"]\n",
        "\n",
        "     },\n",
        "     {\n",
        "       \"tag\": \"good_afternoon\",\n",
        "       \"patterns\": [\"Good afternoon\", \"Afternoon\"],\n",
        "        \"responses\": [\"Good afternoon! How can I assist you today?\"]\n",
        "\n",
        "      },\n",
        "      {\n",
        "      \"tag\": \"good_evening\",\n",
        "      \"patterns\": [\"Good evening\", \"Evening\"],\n",
        "       \"responses\": [\"Good evening! How can I assist you today?\"]\n",
        "\n",
        "         },\n",
        "          {\n",
        "        \"tag\": \"thank_you\",\n",
        "        \"patterns\": [\"Thank you\", \"Thanks\"],\n",
        "        \"responses\": [\"You're welcome! If you have any more questions, feel free to ask.\"]\n",
        "\n",
        "        },\n",
        "       {\n",
        "       \"tag\": \"sorry\",\n",
        "      \"patterns\": [\"Sorry\", \"Apologies\"],\n",
        "       \"responses\": [\"No problem! If there's anything else you need assistance with, feel free to let me know.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"hours\",\n",
        "      \"patterns\": [\"What are the college timings?\", \"When is the college open?\", \"What are your hours of operation?\"],\n",
        "      \"responses\": [\"The college is open from 8am to 5pm, Monday to Saturday.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"contact\",\n",
        "      \"patterns\": [\"How can I contact the college?\", \"What is the college telephone number?\", \"Can I get your contact number?\"],\n",
        "      \"responses\": [\"You can contact the college at 123456789.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"courses\",\n",
        "      \"patterns\": [\"What courses are offered in the college?\", \"Can you tell me about the available courses?\", \"What are the branches in the college?\"],\n",
        "      \"responses\": [\"The college offers courses in Information Technology, Computer Engineering, Mechanical Engineering, Chemical Engineering, and Civil Engineering.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"fees\",\n",
        "      \"patterns\": [\"How much is the college fee?\", \"Tell me about the fees\", \"What are the hostel fees?\"],\n",
        "      \"responses\": [\"For detailed fee information, please visit our college website.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"location\",\n",
        "      \"patterns\": [\"Where is the college located?\", \"What is the college address?\", \"How can I reach the college?\"],\n",
        "      \"responses\": [\"The college is located at [insert address]. You can find the location on Google Maps.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"hostel\",\n",
        "      \"patterns\": [\"Does the college provide hostel facilities?\", \"Where is the hostel located?\", \"What are the hostel fees?\"],\n",
        "      \"responses\": [\"For detailed information about the hostel, please visit our college website.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"events\",\n",
        "      \"patterns\": [\"What events are organized in the college?\", \"Are there any upcoming events?\", \"Tell me about the college events.\"],\n",
        "      \"responses\": [\"For information about the events, please visit our college website.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"admission\",\n",
        "      \"patterns\": [\"What is the admission process?\", \"How can I take admission in the college?\", \"Tell me about the admission criteria.\"],\n",
        "      \"responses\": [\"For detailed admission information, please visit our college website.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"library\",\n",
        "      \"patterns\": [\"Does the college have a library?\", \"Where is the library located?\", \"What are the library timings?\"],\n",
        "      \"responses\": [\"Yes, the college has a library. The library is located [insert location]. The timings are from 9am to 5pm, Monday to Friday.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"facilities\",\n",
        "      \"patterns\": [\"What facilities are available in the college?\", \"Tell me about the college facilities.\", \"Do you have a sports complex?\"],\n",
        "      \"responses\": [\"The college provides various facilities including a sports complex, labs, cafeteria, and a library.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"placement\",\n",
        "      \"patterns\": [\"How are the placements in the college?\", \"Tell me about the college placements.\", \"What is the placement record?\"],\n",
        "      \"responses\": [\"The college has a good placement record. Many reputed companies visit our campus for recruitment.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"school_choice\",\n",
        "      \"patterns\": [\"Why did you choose this school?\", \"What made you decide to attend this college?\"],\n",
        "      \"responses\": [\"I chose this school because of its strong academic reputation, excellent faculty, and a wide range of courses offered.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"happiness\",\n",
        "      \"patterns\": [\"Are you happy here?\", \"Do you enjoy being at this college?\"],\n",
        "      \"responses\": [\"As an AI, I don't have emotions, but I'm here to assist and provide information about the college.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"strengths\",\n",
        "      \"patterns\": [\"What are your school's strengths?\", \"What makes your college stand out?\"],\n",
        "      \"responses\": [\"Our college excels in providing quality education, fostering a supportive learning environment, and offering a wide range of extracurricular activities.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"complaints\",\n",
        "      \"patterns\": [\"What's your #1 complaint about your school?\", \"What do you think needs improvement in your college?\"],\n",
        "      \"responses\": [\"While my purpose is to provide information, some students may have different opinions. It's always good to provide feedback for continuous improvement.\"]\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"improvements\",\n",
        "      \"patterns\": [\"What else could stand to be improved?\", \"In which areas do you think your college can improve?\"],\n",
        "      \"responses\": [\"Continuous improvement is essential for any institution. Areas that can be considered for improvement include infrastructure, facilities, and student support services.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"accessibility\",\n",
        "      \"patterns\": [\"How accessible are administrators, registrars, financial aid officers, etc.?\", \"Can students easily reach out to college staff when needed?\"],\n",
        "      \"responses\": [\"The college administration strives to maintain accessibility for students. Office hours and contact information for various staff members are available for student assistance.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"academics_majors\",\n",
        "      \"patterns\": [\"What majors are popular?\", \"Which fields of study have a high enrollment?\", \"What are the most sought-after majors in your college?\"],\n",
        "      \"responses\": [\"Popular majors in our college include Computer Science, Business Administration, Psychology, Engineering, and Biology.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"academics_reputation\",\n",
        "      \"patterns\": [\"What departments or programs have the best reputations?\", \"Which academic programs are well-regarded?\", \"Are there any standout departments in your college?\"],\n",
        "      \"responses\": [\"Our college has well-regarded departments in Computer Science, Engineering, and Business Administration. These programs have a strong reputation for academic excellence.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"favorite_class\",\n",
        "      \"patterns\": [\"What's your favorite class?\", \"Which class do you enjoy the most?\", \"Do you have a favorite subject?\"],\n",
        "      \"responses\": [\"As an AI, I don't have personal preferences. However, students often enjoy classes that align with their interests and career goals.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"professors_teachers\",\n",
        "      \"patterns\": [\"Are your professors good teachers?\", \"How is the quality of teaching at your college?\", \"Do you have experienced faculty?\"],\n",
        "      \"responses\": [\"Our college prides itself on having experienced and dedicated faculty members who are committed to providing quality education.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"professors_office_hours\",\n",
        "      \"patterns\": [\"Do your professors hold office hours, and will they meet with you outside of class?\", \"Are professors available for one-on-one meetings?\", \"Can students easily meet with professors?\"],\n",
        "      \"responses\": [\"Most professors at our college hold regular office hours and are available for one-on-one meetings to address student queries and provide additional guidance.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"professors_vs_TAs\",\n",
        "      \"patterns\": [\"Are most of your classes taught by professors or teaching assistants?\", \"Who primarily teaches the classes?\", \"Do you have a lot of classes taught by TAs?\"],\n",
        "      \"responses\": [\"The majority of classes at our college are taught by professors. However, in some cases, teaching assistants may assist with course instruction or hold discussion sessions.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"first_choice_classes\",\n",
        "      \"patterns\": [\"Were you able to take most of your first-choice classes?\", \"Do students generally get their preferred classes?\", \"How likely are you to get into your desired classes?\"],\n",
        "      \"responses\": [\"While course availability can vary, our college aims to accommodate students' preferences as much as possible. Course registration is conducted on a first-come, first-served basis.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"class_format\",\n",
        "      \"patterns\": [\"Are your classes lecture-based or discussion-based?\", \"How are the classes structured?\", \"What's the typical format of a class?\"],\n",
        "      \"responses\": [\"The class format can vary depending on the subject and the instructor's teaching style. Some classes may be lecture-based, while others may involve more interactive discussions and group activities.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"reading_writing\",\n",
        "      \"patterns\": [\"How much reading and writing is required in your courses?\", \"Are there a lot of assignments involving reading and writing?\", \"Is there a heavy emphasis on written work?\"],\n",
        "      \"responses\": [\"The amount of reading and writing required in courses can vary. Generally, students can expect a balanced mix of reading assignments, written projects, and exams.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"collaborative_work\",\n",
        "      \"patterns\": [\"How often are collaborative work or group presentations required?\", \"Do you have a lot of group projects?\", \"Is there an emphasis on teamwork?\"],\n",
        "      \"responses\": [\"Collaborative work and group presentations are part of the learning experience at our college. Students often engage in group projects to enhance teamwork and develop important skills.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"academic_advising\",\n",
        "      \"patterns\": [\"How satisfied are you with academic advising?\", \"Is the academic advising program helpful?\", \"Do advisors provide guidance for course selection?\"],\n",
        "      \"responses\": [\"Academic advising plays a crucial role in guiding students' academic journeys. Our college has dedicated advisors who provide assistance with course selection, degree planning, and academic support.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"tutoring_programs\",\n",
        "      \"patterns\": [\"Do students use any on-campus tutoring programs or writing centers?\", \"Are there resources available for academic support?\", \"How can I get tutoring assistance?\"],\n",
        "      \"responses\": [\"Our college provides on-campus tutoring programs and writing centers to support students in their academic endeavors. These resources can help students with subject-specific assistance and writing skills.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"class_size\",\n",
        "      \"patterns\": [\"How big are your classes?\", \"Are the class sizes large or small?\", \"Do you have small class sizes?\"],\n",
        "      \"responses\": [\"Class sizes can vary depending on the course and program. While some classes may have a larger enrollment, others, especially upper-level courses, tend to have smaller class sizes for more personalized attention.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"independent_study\",\n",
        "      \"patterns\": [\"Does your major require an independent study or capstone project?\", \"Are there opportunities for independent research?\", \"Is there a culminating project for your major?\"],\n",
        "      \"responses\": [\"Many majors at our college offer opportunities for independent study or capstone projects. These experiences allow students to delve deeper into their fields of interest and apply their knowledge.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"professor_research\",\n",
        "      \"patterns\": [\"Are professors available for research with students?\", \"Can students engage in research projects with faculty?\", \"How can I get involved in research at your college?\"],\n",
        "      \"responses\": [\"Faculty members at our college actively engage in research, and students often have opportunities to collaborate on research projects. You can reach out to professors in your field of interest to inquire about research opportunities.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"study_abroad\",\n",
        "      \"patterns\": [\"Is it popular to study abroad?\", \"Are there study abroad programs available?\", \"Can students spend a semester abroad?\"],\n",
        "      \"responses\": [\"Studying abroad is a popular option for many students at our college. We offer various study abroad programs and opportunities to experience different cultures and gain international exposure.\"],\n",
        "\n",
        "    },\n",
        "    {\n",
        "      \"tag\": \"first_year_experience\",\n",
        "      \"patterns\": [\"What's it like to be a first-year student here?\", \"Can you describe the first-year experience?\", \"What should I expect as a freshman?\"],\n",
        "      \"responses\": [\"As a first-year s